import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-projects',
  templateUrl: './projects.component.html',
  styleUrls: ['./projects.component.scss'],
})
export class ProjectsComponent implements OnInit {
  projects = [
    {
      title: 'Guess my Number',
      description:
        'Guess my Number is a game in which the player seeks to find the number randomly generated by the computer. for every attempt the computer will give a hint if the guess is too low or too high from the correct number, the score depends on the amount of attempts used to guess the number',
      framework: 'Vanilla JS',
      githubUrl: 'https://github.com/Dev-salav/Guess-my-Number.git',
    },
    {
      title: 'Pig Game',
      description:
        'The Pig Game is a basic dice game in which two players compete each other to reach 21 points. Each turn a player repeatedly rolls a die until either a 1 is rolled or the player holds and scores the sum of the rolls',
      framework: 'Vanilla JS',
      githubUrl: 'https://github.com/Dev-salav/pig-game.git',
    },
    {
      title: 'Todo List',
      description:
        "Todo List it's an application that allows the user to keep control of their personal tasks ",
      framework: 'Angular 2',
      githubUrl: 'https://github.com/Dev-salav/todo-list-NG.git',
    },
    {
      title: 'Recipe-Shopping App',
      description:
        "Recipe-Shopping App it's an application that allows the user to create cooking recipes which can be transform to a shopping list that includes the items and their amounts indicated in the recipe",
      framework: 'Angular 2',
      githubUrl: 'https://github.com/Dev-salav/shopping-app-ng.git',
    },
  ];

  constructor() {}

  ngOnInit(): void {}
}
